services:
  hysteria:
    image: tobyxdd/hysteria
    container_name: hysteria
    restart: on-failure
    network_mode: "host"
    volumes:
      - ./config.yaml:/etc/hysteria/config.yaml:ro
      - ../certs/cert.crt:/etc/hysteria/certs/cert.crt:ro
      - ../certs/private.key:/etc/hysteria/certs/private.key:ro
    command: ["server", "-c", "/etc/hysteria/config.yaml"]
