services:
  tuic-server:
    container_name: tuic-server
    image: monkeyray/tuic:latest
    restart: on-failure
    network_mode: host
    volumes:
      - ./config.json:/etc/tuic/config.json:ro
      - ../certs/cert.crt:/etc/tuic/cert.crt:ro
      - ../certs/private.key:/etc/tuic/private.key:ro
